# Generated by Django 4.2.30 on 2026-05-28 00:43

import apps.common.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('view_content', 'View Content'), ('add_to_cart', 'Add to Cart'), ('initiate_checkout', 'Initiate Checkout'), ('purchase', 'Purchase'), ('lead', 'Lead')], max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metadata', apps.common.fields.SQLiteSafeJSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'conversion_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.CharField(max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('device', models.CharField(blank=True, max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'db_table': 'page_views',
                'ordering': ['-created_at'],
            },
        ),
    ]
