# Generated by Django 4.2.30 on 2026-06-16 02:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_ab_test_product_b_product_enable_ab_test'),
        ('stores', '0008_storeworker'),
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionInteractionEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('impression', 'Section Impression'), ('click', 'Section Click')], default='impression', max_length=20)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_interactions', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'db_table': 'section_interaction_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'product', 'section_type'], name='section_int_store_i_0791bb_idx')],
            },
        ),
    ]
