# Generated by Django 4.2.30 on 2026-05-28 00:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixelConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('meta', 'Meta Pixel'), ('tiktok', 'TikTok Pixel'), ('snapchat', 'Snapchat Pixel')], max_length=20)),
                ('pixel_id', models.CharField(max_length=255)),
                ('access_token', models.TextField(blank=True, help_text='Required for Conversions API integrations (optional)')),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'db_table': 'pixel_configs',
                'unique_together': {('store', 'platform')},
            },
        ),
    ]
