# Generated by Django 4.2.30 on 2026-05-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('pixels', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pixelconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pixelconfig',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pixelconfig',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pixels', to='products.product'),
        ),
    ]
