# Generated by Django 4.2.30 on 2026-07-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0002_alter_pixelconfig_unique_together_pixelconfig_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixelconfig',
            name='test_event_code',
            field=models.CharField(blank=True, help_text='Optional Meta Test Event Code (e.g. TEST12345)', max_length=100, null=True),
        ),
    ]
