# Generated by Django 4.2.30 on 2026-05-28 00:43

import apps.common.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.URLField(blank=True)),
                ('preview_url', models.URLField(blank=True)),
                ('is_free', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.CharField(default='S Platform', max_length=100)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('template_config', apps.common.fields.SQLiteSafeJSONField(blank=True, default=dict, help_text='Theme color and layout config')),
                ('supports_rtl', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'themes',
                'ordering': ['-created_at'],
            },
        ),
    ]
