# Generated by Django 4.2.30 on 2026-05-28 00:43

import apps.common.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('product', models.ForeignKey(blank=True, help_text='Associate this landing page with a direct product checkout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'db_table': 'landing_pages',
                'unique_together': {('store', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Banner'), ('product_gallery', 'Product Gallery'), ('carousel', 'Carousel'), ('reviews', 'Reviews'), ('faq', 'FAQ'), ('video', 'Video Section'), ('comparison', 'Comparison Section'), ('benefits', 'Benefits Section'), ('before_after', 'Before/After Section'), ('countdown', 'Countdown Timer'), ('sticky_cta', 'Sticky CTA'), ('quantity_offers', 'Quantity Offers'), ('bundle_offers', 'Bundle Offers'), ('delivery_info', 'Delivery Information'), ('text', 'Text Section'), ('image', 'Image Section'), ('floating_order_button', 'Floating Order Button')], max_length=30)),
                ('position', models.PositiveIntegerField(default=0)),
                ('config', apps.common.fields.SQLiteSafeJSONField(blank=True, default=dict, help_text='JSON configuration for this section style and text contents')),
                ('is_enabled', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.landingpage')),
            ],
            options={
                'db_table': 'page_sections',
                'ordering': ['position'],
            },
        ),
    ]
