# Generated by Django 4.2.30 on 2026-06-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon_code_order_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('no_answer', 'Client Not Answering'), ('postponed', 'Confirmation Postponed'), ('confirmed', 'Confirmed'), ('pending', 'Pending'), ('prepared', 'Prepared'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='new', max_length=15),
        ),
    ]
