# Generated by Django 4.2.30 on 2026-06-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_inventory_deducted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('no_answer', 'Client Not Answering'), ('no_answer_1', 'Client Not Answering (Call 1)'), ('no_answer_2', 'Client Not Answering (Call 2)'), ('no_answer_3', 'Client Not Answering (Call 3)'), ('postponed', 'Confirmation Postponed'), ('confirmed', 'Confirmed'), ('pending', 'Pending'), ('prepared', 'Prepared'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='new', max_length=15),
        ),
    ]
