# Generated by Django 4.2.30 on 2026-07-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
    ]
