# Generated by Django 4.2.30 on 2026-08-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(default='home', help_text='home or desk delivery', max_length=20),
        ),
    ]
