# Generated by Django 4.2.30 on 2026-06-19 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0008_storeworker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('baridimob_ccp', 'BaridiMob / CCP'), ('redotpay', 'RedotPay')], max_length=50)),
                ('receipt_image', models.ImageField(upload_to='receipts/')),
                ('amount_da', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name_ar', models.CharField(max_length=100)),
                ('price_da', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trial_days', models.IntegerField(default=7)),
                ('max_products', models.IntegerField(default=-1)),
                ('max_workers', models.IntegerField(default=-1)),
                ('max_pixels', models.IntegerField(default=-1)),
                ('max_orders_per_month', models.IntegerField(default=-1)),
                ('has_variants', models.BooleanField(default=True)),
                ('has_ab_testing', models.BooleanField(default=True)),
                ('has_coupons', models.BooleanField(default=True)),
                ('has_custom_domain', models.BooleanField(default=False)),
                ('has_advanced_analytics', models.BooleanField(default=False)),
                ('has_otp', models.BooleanField(default=False)),
                ('has_captcha', models.BooleanField(default=False)),
                ('has_rate_limit', models.BooleanField(default=False)),
                ('has_algerian_ip', models.BooleanField(default=False)),
                ('has_sticky_cta', models.BooleanField(default=True)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_multi_store', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_trial', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('payment_pending', 'Payment Pending')], default='trial', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('notified_24h', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.paymentreceipt')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='stores.store')),
            ],
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plan'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='stores.store'),
        ),
    ]
