# Generated by Django 4.2.30 on 2026-05-28 00:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_fr', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'communes',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('yalidine', 'Yalidine'), ('zr_express', 'ZR Express'), ('noest', 'Noest'), ('ems', 'EMS'), ('ecolog', 'Ecolog'), ('guepex', 'Guepex'), ('manual', 'Manual')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('api_base_url', models.URLField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_tracking', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery companies',
                'db_table': 'delivery_companies',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPricing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desk_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'delivery_pricing',
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(db_index=True, unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_fr', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'wilayas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StoreDeliveryConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.CharField(blank=True, help_text='API key provided by delivery company', max_length=500)),
                ('api_secret', models.CharField(blank=True, help_text='API secret/token', max_length=500)),
                ('api_id', models.CharField(blank=True, help_text='API ID (e.g., Yalidine API ID)', max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_configs', to='delivery.deliverycompany')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'db_table': 'store_delivery_configs',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('created', 'Created'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('failed', 'Failed')], default='created', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('label_url', models.URLField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverycompany')),
            ],
            options={
                'db_table': 'shipments',
            },
        ),
    ]
