# Generated by Django 4.2.30 on 2026-06-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_deliverycompany_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycompany',
            name='name',
            field=models.CharField(choices=[('yalidine', 'Yalidine'), ('zr_express', 'ZR Express'), ('noest', 'Noest'), ('ems', 'EMS'), ('ecolog', 'Ecolog'), ('guepex', 'Guepex'), ('gupex', 'Gupex'), ('maystro_delivery', 'Maystro Delivery'), ('dhd', 'DHD'), ('yaliteck', 'Yaliteck'), ('flash_delivery', 'Flash Delivery'), ('manual', 'Manual Settings'), ('ecom_delivery', 'Ecom Delivery')], max_length=50, unique=True),
        ),
    ]
