# Generated by Django
from django.db import migrations

def rename_ain_azel(apps, schema_editor):
    Wilaya = apps.get_model('delivery', 'Wilaya')
    Commune = apps.get_model('delivery', 'Commune')
    
    try:
        setif = Wilaya.objects.get(code=19)
        Commune.objects.filter(wilaya=setif, name_fr='Ain Azel').update(name_fr='Ain Azal')
    except Exception:
        pass

class Migration(migrations.Migration):
    dependencies = [
        ('delivery', '0004_alter_deliverycompany_name'),
    ]

    operations = [
        migrations.RunPython(rename_ain_azel),
    ]
