# Generated by Django 4.2.30 on 2026-07-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_rename_ain_azel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycompany',
            name='name',
            field=models.CharField(choices=[('yalidine', 'Yalidine'), ('zr_express', 'ZR Express'), ('ems', 'EMS'), ('manual', 'Manual Settings'), ('ecom_delivery', 'Ecom Delivery'), ('maystro_delivery', 'Maystro Delivery'), ('flash_delivery', 'Flash Delivery'), ('noest', 'Noest'), ('ecolog', 'Ecolog'), ('guepex', 'Guepex'), ('gupex', 'Gupex'), ('dhd', 'DHD'), ('yaliteck', 'Yaliteck'), ('48hr_livraison', '48hr Livraison'), ('allo_livraison', 'Allo Livraison'), ('anderson_delivery', 'Anderson Delivery'), ('areex', 'Areex'), ('assil_delivery', 'Assil Delivery'), ('baconsult', 'BaConsult'), ('colireli', 'Colireli'), ('colivraison_express', 'Colivraison Express'), ('coyote_express', 'Coyote Express'), ('delivromail', 'Delivromail'), ('dhd_express', 'DHD Express'), ('distazero', 'Distazero'), ('expedia_chrono', 'Expedia Chrono'), ('fretdirect', 'Fretdirect'), ('fz_delivery', 'FZ Delivery'), ('golivri', 'Golivri'), ('hhd_express', 'HHD Express'), ('imir', 'Imir'), ('medexpress', 'MedExpress'), ('monohub', 'MonoHub'), ('msm_go', 'MSM Go'), ('navex_delivery', 'Navex Delivery'), ('negmar_express', 'Negmar Express'), ('noest_express', 'Noest Express'), ('om_express', 'OM Express'), ('ontime_ecotrack', 'Ontime EcoTrack'), ('packers', 'Packers'), ('pdex', 'Pdex'), ('prest', 'Prest'), ('rb_livraison', 'RB Livraison'), ('rex_livraison', 'Rex Livraison'), ('rocket_delivery', 'Rocket Delivery'), ('salva_delivery', 'Salva Delivery'), ('samex_delivery', 'SamEx Delivery'), ('speed_delivery', 'Speed Delivery'), ('swift_express', 'Swift Express'), ('tsl_express', 'TSL Express'), ('ultra_express', 'Ultra Express'), ('univer_delivery', 'Univer Delivery'), ('worldexpress', 'Worldexpress'), ('zvit_express', 'Z-Vit Express')], max_length=50, unique=True),
        ),
    ]
