# Generated by Django 4.2.30 on 2026-05-28 00:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spreadsheet_id', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(default='Orders', max_length=100)),
                ('credentials_json', models.TextField(blank=True, help_text='Service account credentials JSON')),
                ('is_active', models.BooleanField(default=False)),
                ('sync_on_create', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'verbose_name': 'Google Sheets Config',
                'db_table': 'google_sheets_configs',
            },
        ),
    ]
