# Generated by Django 4.2.30 on 2026-06-20 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_storeworker'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaudeConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('auto_fraud_check', models.BooleanField(default=False)),
                ('auto_draft_replies', models.BooleanField(default=False)),
                ('auto_product_copy', models.BooleanField(default=False)),
                ('system_prompt', models.TextField(blank=True, default='You are Claude, a helpful AI assistant integrated into Sovi - a SaaS Algerian E-Commerce Platform.')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'verbose_name': 'Claude Config',
                'db_table': 'claude_configs',
            },
        ),
    ]
