# Generated by Django 4.2.30 on 2026-06-23 21:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_storeworker'),
        ('integrations', '0002_claudeconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_token', models.CharField(blank=True, max_length=255)),
                ('chat_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('send_on_create', models.BooleanField(default=True)),
                ('send_on_status_change', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'verbose_name': 'Telegram Config',
                'db_table': 'telegram_configs',
            },
        ),
    ]
