# Generated by Django 4.2.30 on 2026-06-20 17:20

import apps.common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0008_storeworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_api_keys', to='stores.store')),
            ],
            options={
                'db_table': 'mcp_api_keys',
            },
        ),
        migrations.CreateModel(
            name='McpToolCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=255)),
                ('arguments', apps.common.fields.SQLiteSafeJSONField(blank=True, default=dict)),
                ('result_summary', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_calls', to='mcp_server.mcpapikey')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tool_calls', to='stores.store')),
            ],
            options={
                'db_table': 'mcp_tool_call_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
