# Generated by Django 4.2.30 on 2026-06-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(db_index=True, help_text='Official Algerian wilaya number (1-58)', unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Wilaya',
                'verbose_name_plural': 'Wilayas',
                'db_table': 'locations_wilaya',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='wilaya_code_idx'), models.Index(fields=['name'], name='wilaya_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='locations.wilaya')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'db_table': 'locations_commune',
                'ordering': ['wilaya__code', 'name'],
                'indexes': [models.Index(fields=['wilaya', 'name'], name='commune_wilaya_name_idx'), models.Index(fields=['name'], name='commune_name_idx')],
                'unique_together': {('wilaya', 'name')},
            },
        ),
    ]
