# Generated by Django
from django.db import migrations

def rename_ain_azel(apps, schema_editor):
    Wilaya = apps.get_model('locations', 'Wilaya')
    Commune = apps.get_model('locations', 'Commune')
    
    try:
        setif = Wilaya.objects.get(code=19)
        Commune.objects.filter(wilaya=setif, name='Ain Azel').update(name='Ain Azal')
    except Exception:
        pass

class Migration(migrations.Migration):
    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rename_ain_azel),
    ]
