# Generated by Django 4.2.30 on 2026-05-28 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('subdomain', models.CharField(db_index=True, max_length=63, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('favicon', models.URLField(blank=True)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('fr', 'French'), ('en', 'English')], default='ar', max_length=2)),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar')], default='DZD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('active_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_stores', to='themes.theme')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#8b5cf6', max_length=7)),
                ('custom_css', models.TextField(blank=True)),
                ('thank_you_message', models.TextField(default='Thank you for your order! We will contact you shortly.')),
                ('confirmation_message', models.TextField(default='Your order has been confirmed.')),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.store')),
            ],
            options={
                'db_table': 'store_settings',
            },
        ),
    ]
