# Generated by Django 4.2.30 on 2026-06-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='security_captcha_secret_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='security_captcha_site_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='security_enable_captcha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='security_enable_phone_validation',
            field=models.BooleanField(default=False),
        ),
    ]
