# Generated by Django 4.2.30 on 2026-06-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storesettings_security_captcha_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='security_enable_firebase_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='security_firebase_config_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
