# Generated by Django 4.2.30 on 2026-06-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_storesettings_security_enable_firebase_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='security_block_non_algerian_ips',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='security_max_orders_per_day',
            field=models.IntegerField(default=5),
        ),
    ]
