# Generated by Django 4.2.30 on 2026-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_storesettings_security_block_non_algerian_ips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='announcement_bg_color',
            field=models.CharField(default='#4f46e5', max_length=7),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='announcement_text',
            field=models.CharField(default='الدفع عند الاستلام في 58 ولاية!', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='badge_1_desc',
            field=models.CharField(default='التوصيل لجميع الولايات بأسعار مدروسة.', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='badge_1_title',
            field=models.CharField(default='توصيل سريع', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='badge_2_desc',
            field=models.CharField(default='لا تدفع أي شيء حتى تستلم منتجك بين يديك.', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='badge_2_title',
            field=models.CharField(default='الدفع عند الاستلام', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='badge_3_desc',
            field=models.CharField(default='فريق عملنا متواجد للرد على اتصالاتكم وتأكيد الطلبيات.', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='badge_3_title',
            field=models.CharField(default='دعم العملاء', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_floating_button',
            field=models.BooleanField(default=True),
        ),
    ]
