# Generated by Django 4.2.30 on 2026-06-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_storesettings_announcement_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='homepage_sections',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
