# Generated by Django 4.2.30 on 2026-06-12 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0007_storesettings_homepage_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWorker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_manage_products', models.BooleanField(default=False)),
                ('can_manage_orders', models.BooleanField(default=False)),
                ('can_manage_delivery', models.BooleanField(default=False)),
                ('can_manage_pages', models.BooleanField(default=False)),
                ('can_manage_themes', models.BooleanField(default=False)),
                ('can_manage_pixels', models.BooleanField(default=False)),
                ('can_manage_integrations', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('can_manage_workers', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_workers',
                'unique_together': {('store', 'user')},
            },
        ),
    ]
