# Generated by Django 4.2.30 on 2026-06-01 20:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badges',
            field=models.TextField(blank=True, default='', help_text='Comma-separated: best_seller,new_arrival,limited_edition,...'),
        ),
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image / Carousel'), ('reviews', 'Reviews'), ('before_after', 'Before / After Slider'), ('bundles', 'Bundle Creator'), ('features', 'Product Features')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('config', models.TextField(blank=True, default='{}')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='products.product')),
            ],
            options={
                'db_table': 'product_sections',
                'ordering': ['order'],
            },
        ),
    ]
