# Generated by Django 4.2.30 on 2026-06-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_badges_productsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='theme',
            field=models.CharField(blank=True, default='', help_text='Product page theme class name', max_length=50),
        ),
    ]
