# Generated by Django 4.2.30 on 2026-06-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ad_cost_per_order',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
