# Generated by Django 4.2.30 on 2026-06-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productsection_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsection',
            name='section_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image / Carousel'), ('reviews', 'Reviews'), ('before_after', 'Before / After Slider'), ('bundles', 'Bundle Creator'), ('features', 'Product Features'), ('product_info', 'Product Info'), ('quantity_offers', 'Quantity Offers'), ('checkout', 'Order Form'), ('security_option', 'Security Option')], max_length=20),
        ),
    ]
