# Generated by Django 4.2.30 on 2026-06-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productsection_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsection',
            name='section_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image / Carousel'), ('reviews', 'Reviews'), ('before_after', 'Before / After Slider'), ('bundles', 'Bundle Creator'), ('features', 'Product Features'), ('product_info', 'Product Info'), ('quantity_offers', 'Quantity Offers'), ('checkout', 'Order Form'), ('security_captcha', 'Security: reCAPTCHA v3'), ('security_phone_validation', 'Security: Phone Format Validation'), ('security_otp', 'Security: Firebase SMS OTP'), ('security_rate_limit', 'Security: Rate Limit (Orders/IP)'), ('security_algerian_ip', 'Security: Algerian IPs Only'), ('footer', 'Footer')], max_length=50),
        ),
    ]
