# Generated by Django 4.2.30 on 2026-06-15 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ab_test_product_b',
            field=models.ForeignKey(blank=True, help_text='Alternative product layout for Group B', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_ab_test',
            field=models.BooleanField(default=False, help_text='Enable A/B split-testing for this product'),
        ),
    ]
