# Generated by Django 4.2.30 on 2026-06-17 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_storeworker'),
        ('products', '0012_product_ab_test_product_b_product_enable_ab_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsection',
            name='section_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image / Carousel'), ('reviews', 'Reviews'), ('before_after', 'Before / After Slider'), ('bundles', 'Bundle Creator'), ('features', 'Product Features'), ('product_info', 'Product Info'), ('quantity_offers', 'Quantity Offers'), ('checkout', 'Order Form'), ('security_captcha', 'Security: reCAPTCHA v3'), ('security_phone_validation', 'Security: Phone Format Validation'), ('security_otp', 'Security: Firebase SMS OTP'), ('security_rate_limit', 'Security: Rate Limit (Orders/IP)'), ('security_algerian_ip', 'Security: Algerian IPs Only'), ('footer', 'Footer'), ('header', 'Header'), ('coupon', 'Coupon / Discount Code')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_city', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('body', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved reviews appear on the storefront')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='stores.store')),
            ],
            options={
                'db_table': 'product_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
